namespace Sim.Enums {
    public enum ActionTypeEnum
    {
        MOVE,
        SIT,
        COUCH,
        LOOK,
        BUILD,
        SELL,
        LOCK,
        PAINT,
        OPEN,
        TELEPORT,
        UNPACKAGE,
        PICK,
        EAT,
        DROP,
        DRINK,
        USE,
        RING,
        UNLOCK,
        LIST_FOR_SALE,
        UNLIST,
        BUY,
        DESTROY,
        CLEAN,
        THROW,
        MAKE_ACQUAINTANCE,
        MAKE_CONTACT,
        VIEW_IDENTITY,
        TOGGLE_MUTE,
        GIVE_MONEY,
        REPACK,
        UNPACK,
        ENTER_VEHICLE,
        EXIT_VEHICLE
    }

}
